//Copyright (C) 2014 Panasonic Corporation. All Rights Reserved.////*****************************************************************/// File Name: cooking_detail.js// Purpose: This document creates the detail page// File Created Date: 28-Apr-2014// Release Date: 10-Jun-2014// Release Version: 0.3//*****************************************************************/var detail={contentType:"",contentTitle:"",disable:0,oldCursor:"",prevCursor:"",tempArr:[],titlePage:0,timer:""};detail.descriptionContainer=function(){"use strict";var divLineHeight=50,lines=13,scrollVal=0,arrow=null,jsonData={},top=0,descData={};this.replaceDelimiter=function(desc){var str=desc.replace(/\r\n/g,"<br/>"),lastInd,sum;str=str.replace(/<br\/><br\/>/g,"<br/>");lastInd=str.lastIndexOf("<br/>");sum=parseInt(lastInd)+5;if(str.length===sum&&lastInd!=-1){str=str.substring(0,lastInd);}
return str;};this.replaceSteps=function(desc){var str=desc,lastInd,sum;str=str.replace(/\r\n/g,"<br/>");lastInd=str.lastIndexOf("<br/>");sum=parseInt(lastInd)+5;if(str.length===sum&&lastInd!=-1){str=str.substring(0,lastInd);}
return str;}
this.startScrollText=function(){var self=this;if(detail.tempArr.length>1){detail.timer=setInterval(function(){self.startTimer();},5000);}};this.startTimer=function(){document.getElementById('headerTitle').innerHTML="";document.getElementById('headerTitle').innerHTML=detail.tempArr[detail.titlePage];detail.titlePage+=1;var arrLength=(detail.tempArr.length)-1;if(detail.titlePage>arrLength){detail.titlePage=0;}}
this.stopScrollText=function(){clearInterval(detail.timer);};this.setTheme=function(){var loopVar;$('.theme').css("background-color",main.theme);$(".descHeader").css("color",main.theme);};this.setDescriptionData=function(){var i=0;descData={"description":"","ingredients":"","stepsToMake":""};descData.description=(jsonData.Result[main.selectedGrid].Description)?this.replaceDelimiter(jsonData.Result[main.selectedGrid].Description):"NO DESCRIPTION AVAILABLE.";if(jsonData.Result[main.selectedGrid].Items&&jsonData.Result[main.selectedGrid].Items.length>0){for(i=0;i<jsonData.Result[main.selectedGrid].Items.length;i++){descData.ingredients+=(jsonData.Result[main.selectedGrid].Items[i]&&jsonData.Result[main.selectedGrid].Items[i].Quantity)?jsonData.Result[main.selectedGrid].Items[i].Quantity:"";descData.ingredients+=(jsonData.Result[main.selectedGrid].Items[i]&&jsonData.Result[main.selectedGrid].Items[i].Measurement)?jsonData.Result[main.selectedGrid].Items[i].Measurement+" ":"";descData.ingredients+=(jsonData.Result[main.selectedGrid].Items[i]&&jsonData.Result[main.selectedGrid].Items[i].Description)?this.replaceDelimiter(jsonData.Result[main.selectedGrid].Items[i].Description)+"<br/>":"";}
if(descData.ingredients===""){descData.ingredients="NO ITEMS AVAILABLE.";}}else{descData.ingredients="NO ITEMS AVAILABLE.";}
descData.stepsToMake=(jsonData.Result[main.selectedGrid].Steps)?this.replaceSteps(jsonData.Result[main.selectedGrid].Steps):"NO STEPS AVAILABLE.";detail.uniqueKey=(jsonData.Result[main.selectedGrid].UniqueKey?jsonData.Result[main.selectedGrid].UniqueKey:null);};this.setProductDesc=function(){descData={"productDesc":"NO PRODUCT DESCRIPTION AVAILABLE."};descData.description=(jsonData.Result[main.selectedGrid].RecommendedProduct.Description)?this.replaceDelimiter(jsonData.Result[main.selectedGrid].RecommendedProduct.Description):"NO PRODUCT DESCRIPTION AVAILABLE.";if(jsonData.Result[main.selectedGrid].RecommendedProduct.Medias&&jsonData.Result[main.selectedGrid].RecommendedProduct.Medias.length>0){detail.galleryObj.productGallery(jsonData);}};this.setFontColor=function(){$("#detailTitle").removeClass('nonFocus');if(detail.contentType=="Recipe"){$("#detailTitle").addClass('recipeFont');}else if(detail.contentType=="FoodHack"){$("#detailTitle").addClass('foodHackFont');}else if(detail.contentType=="Product"){$("#detailTitle").addClass('productFont');}else if(detail.contentType=="Gallery"){$("#detailTitle").addClass('galleryFont');}else{$("#detailTitle").addClass('defaultFont');}};this.setDefaultColor=function(){$("#detailTitle").addClass("nonFocus");if(detail.contentType=="Recipe"){$("#detailTitle").removeClass('recipeFont');}else if(detail.contentType=="FoodHack"){$("#detailTitle").removeClass('foodHackFont');}else if(detail.contentType=="Product"){$("#detailTitle").removeClass('productFont');}else if(detail.contentType=="Gallery"){$("#detailTitle").removeClass('galleryFont');}else{$("#detailTitle").removeClass('defaultFont');}};this.enter_focus=function(){main.focusedDom=this;this.setFontColor();$(".rightCont").addClass("rightCont_cur");$(".arrowContainer").addClass("rightCont_cur");$(".rightCont").css("background-color",main.theme);$(".hotKeyContainer").css("background-color","#dddddd");$(".hotkeyCont").css("visibility","visible");$("#arrowContainer").css("background-color",main.theme);$(".arrowDivider").css("background-color","#e2e2e2");$("#opacityDiv").removeClass('hide');if($("#upArr").hasClass(detail.enableUpArrCur)){$("#upArr").removeClass(detail.enableUpArrCur);$("#upArr").addClass("enableUpArr");}
if($("#downArr").hasClass(detail.enableDownArrCur)){$("#downArr").removeClass(detail.enableDownArrCur);$("#downArr").addClass("enableUpArr");}};this.leave_focus=function(){this.setDefaultColor();$(".rightCont").removeClass("rightCont_cur");$(".arrowContainer").removeClass("rightCont_cur");$(".rightCont").css("background-color","");$(".hotKeyContainer").css("background-color","#fff");$("#arrowContainer").css("background-color","#dddddd");$(".arrowDivider").css("background-color","#c7c7c7");$(".hotkeyCont").css("visibility","hidden");$("#opacityDiv").addClass('hide');if($("#upArr").hasClass("enableUpArr")){$("#upArr").removeClass("enableUpArr");$("#upArr").addClass(detail.enableUpArrCur);}
if($("#downArr").hasClass("enableUpArr")){$("#downArr").removeClass("enableUpArr");$("#downArr").addClass(detail.enableDownArrCur);}};this.disableMenu=function(){detail.disable=0;if(!jsonData.Result[main.selectedGrid].RecommendedProduct){$("#icon_2").addClass('disabled');$("#icon_2").addClass('icon_2_disabled');$("#shaded_2").addClass("shaded_disabled");$(".shaded_2").css("background-position","0 -1092px");detail.disable++;}
if(!jsonData.Result[main.selectedGrid].CommentCount||jsonData.Result[main.selectedGrid].CommentCount===0||!detail.uniqueKey){$("#icon_3").addClass('disabled');$("#icon_3").addClass('icon_3_disabled');$("#shaded_3").addClass("shaded_disabled");$(".shaded_3").css("background-position","0 -582px");detail.disable++;}
if(detail.disable===2){detail.prev=(detail.galleryObj.components.length>1||detail.hasVideo?detail.galleryObj:null);}else{detail.prev=detail.menuObj;}};this.createDescription=function(data){var desc="";this.freeTextArea();if(data){jsonData=data;}
if(detail.prevSelected===2){detail.galleryObj.thumbnail(jsonData);}
detail.prevSelected=1;this.setDescriptionData();desc="<div id='contentText'><span id='desc' class='descHeader'>DESCRIPTION<br></span><span id='descText'>"+descData.description+"</span>";if(detail.contentType!=="Gallery"&&detail.contentType!=="Product"&&detail.contentType!=="Feature"){desc+="<br/><span><img class='divider' src='images/bg_box.png'/></span><span id='steps' class='descHeader'>ITEMS REQUIRED<br></span><span>"+descData.ingredients+"</span><span><img class='divider' src='images/bg_box.png'/></span><span id='howTomake' class='descHeader'>STEPS</span><br><span>"+descData.stepsToMake+"</span></div>";}else{desc+="</div>";}
descContainer.innerHTML+=desc;if(main.selectedCountry=="MALAYSIA"&&detail.contentType=="Gallery"){subCategory.innerHTML="FOOD DIARY DETAILS";}else{subCategory.innerHTML=detail.contentType.toUpperCase()+" DETAILS";}
arrow=detail.createArrow();this.enter_focus();detail.first=false;$(".shaded_selected").css("background-color",detail.icon);this.setTheme();};this.createProductDesc=function(){var desc="";this.freeTextArea();this.setProductDesc();desc="<div id='contentText'><span id='desc' class='descHeader'>DESCRIPTION<br></span><span id='descText'>"+descData.description+"</span><br/></div>";descContainer.innerHTML+=desc;subCategory.innerHTML="PRODUCT DETAILS";arrow=detail.createArrow();this.enter_focus();$(".shaded_selected").css("background-color",detail.icon);this.setTheme();};function comments_baseGrid(param){var config=param||{},pg_num=0,curPgBal=0,availHeight=0,curHeight=0,heightVal=0,newPg,page="<div id='page_"+config.id+"' class='pageContainer'></div>";contentText.innerHTML+=page;page="<span id='comment_"+config.id+"' class='commentData'><span id=imgCont_"+config.id+"' class='imgCont'><div class='imgLoading' id='imgLoading_"+config.id+"'>Loading...</div><img id='profilePic_"+config.id+"' onload='imgOnload(this)' onerror='imgOnerror(this)' class='profilePic' src='"+config.src+"'/></span><span id='commentsCont_"+config.id+"' class='commentsCont'><span id='userName_"+config.id+"' class='userName'>"+config.name+"</span><br/>"+config.text+"</span><span><img src='images/bg_box.png' class='divider'/></span></span>";document.getElementById('page_'+config.id).innerHTML+=page;heightVal=$("#contentText").height();pg_num=Math.ceil(heightVal/650);curPgBal=heightVal-((pg_num-1)*650);availHeight=650-curPgBal;if(availHeight<138){curHeight=$("#page_"+config.id).height();curHeight=curHeight+availHeight;$("#page_"+config.id).css("height",curHeight);}
newPg=1;var imgOnload=function(image){$(image).prev().css("display","none");}
var imgOnerror=function(image){$(image).prev().css("display","none");$(image).attr("src","images/default_image.png");}}
this.createComments=function(data){var item=0,comments="<div id='contentText'></div>";this.freeTextArea();descContainer.innerHTML+=comments;if(detail.prevSelected===2){detail.galleryObj.thumbnail(jsonData);}
if(data&&data.StatusCode===100){for(item=0;item<data.Result.length;item++){comments_baseGrid({'id':item,'src':(data.Result[item]&&data.Result[item].Commentor&&data.Result[item].Commentor.AvatarUri)?data.Result[item].Commentor.AvatarUri:"images/default_image.png",'text':(data.Result[item]&&data.Result[item].Text)?data.Result[item].Text:"NO COMMENT AVAILABLE.",'name':(data.Result[item]&&data.Result[item].Commentor&&data.Result[item].Commentor.Name)?data.Result[item].Commentor.Name:"Unknown user"});}}else{contentText.innerHTML="<div class='errIcon'></div><div class='commentsErr'>NETWORK CONNECTION FAILURE.</div>";}
subCategory.innerHTML="COMMENTS";arrow=detail.createArrow();this.enter_focus();$(".shaded_selected").css("background-color",detail.icon);$(".userName").css("color",main.theme);this.setTheme();};this.freeTextArea=function(){descContainer.innerHTML="";$("#arrCont").remove();subCategory.innerHTML="";scrollVal=0;};this.scrollUp=function(){scrollVal-=((lines)*divLineHeight);try{$("#contentText").css("margin-top",scrollVal);}catch(e){}
detail.pageDetails.currentPg+=1;arrow.setPage(detail.pageDetails.currentPg);};this.scrollDown=function(){scrollVal+=(lines)*divLineHeight;$("#contentText").css("margin-top",scrollVal);detail.pageDetails.currentPg-=1;arrow.setPage(detail.pageDetails.currentPg);};this.KeyboardEvent=function(e,eventType){try{var target=main.target(e),keyCode=target.keyCode,key=main.keyCodeDic[keyCode];if(eventType==="keydown"){switch(key){case"arrowdown":if(detail.pageDetails.totalPage>1&&detail.pageDetails.currentPg!==detail.pageDetails.totalPage){this.scrollUp();}
return false;case"arrowup":if(detail.pageDetails.totalPage>1&&detail.pageDetails.currentPg!==1){this.scrollDown();}else{detail.oldCursor=this;detail.prevCursor=this;this.leave_focus();main.mainBg.enter_focus();}
return false;case"arrowleft":if(detail.prev||detail.hasVideo){this.leave_focus();detail.prev.enter_focus();}
return false;}
return false;}}catch(e){}};};detail.descObj=new detail.descriptionContainer();detail.createArrow=function(){"use strict";var obj={},arrowContainer="<div id='arrCont' class='arrCont'><div class='hotKeyBg'><div id='arrowContainer' class='arrowContainer theme'><div id='upArr' class='arrow disabledUpArr'></div><div class='redHotKeyCont hotkeyCont'></div><div class='redHotKey hotKey'></div><div id='arrowDivider' class='arrowDivider'></div><div id='downArr' class='arrow'></div><div class='greenHotKeyCont hotkeyCont'></div><div class='greenHotKey hotKey'></div></div></div><div id='pageCont' class='pageCont'></div></div>",totalPage=0,currentPg=1;detailRight.innerHTML+=arrowContainer;obj.enableupArrow=function(){$("#upArr").removeClass("disabledUpArr");$(".redHotKey").removeClass("opacity_blur");$(".redHotKey").addClass("opacity_one");if(main.focusedDom===detail.descObj){$("#upArr").addClass("enableUpArr");}else{$("#upArr").addClass(detail.enableUpArrCur);}};obj.enabledownArrow=function(){$("#downArr").removeClass("disabledUpArr");$(".greenHotKey").removeClass("opacity_blur");$(".greenHotKey").addClass("opacity_one");if(main.focusedDom===detail.descObj){$("#downArr").addClass("enableUpArr");}else{$("#downArr").addClass(detail.enableUpArrCur);}};obj.enableBothArrow=function(){obj.enabledownArrow();obj.enableupArrow();};obj.DisableBothArrow=function(){if(main.focusedDom===detail.descObj){$("#upArr").removeClass("enableUpArr");$("#downArr").removeClass("enableUpArr");}else{$("#upArr").removeClass(detail.enableUpArrCur);$("#downArr").removeClass(detail.enableUpArrCur);}
$("#upArr").addClass("disabledUpArr");$("#downArr").addClass("disabledUpArr");$(".greenHotKey").removeClass("opacity_one");$(".greenHotKey").addClass("opacity_blur");$(".redHotKey").removeClass("opacity_one");$(".redHotKey").addClass("opacity_blur");};obj.hideArrow=function(){$("#arrCont").css("display","none");};obj.setArrow=function(){obj.DisableBothArrow();if(currentPg===1){obj.enabledownArrow();}else if(currentPg===totalPage){obj.enableupArrow();}else{obj.enableBothArrow();}};obj.setPage=function(current){var pageWidth=0;currentPg=current;pageCont.innerHTML="<div class='pgCont'><div class='curPg detailPages'>"+current+"&nbsp;</div><div class='pageDivider detailPages'></div><div class='ttlPg detailPages'>&nbsp;"+totalPage+"</div></div>";pageWidth=parseInt($(".curPg").css("width"))+1+parseInt($(".ttlPg").css("width"));$(".pgCont").css("width",pageWidth);obj.setArrow();detail.pageDetails=this.getPage();};obj.getPage=function(){return{currentPg:currentPg,totalPage:totalPage};};obj.findTotalPage=function(){return Math.ceil(contentText.clientHeight/650);};totalPage=obj.findTotalPage();if(totalPage>1){obj.enabledownArrow();}else{obj.hideArrow();}
obj.setPage(1);return obj;};detail.menuContainer=function(){"use strict";var openedIndex=1,curFocus=1;this.setLabelDivider=function(param){$("#label_"+param).removeClass("labelBg");$("#scroller_"+param).removeClass("labelBg");$("#label_"+param).addClass("menuDivider");$("#scroller_"+param).addClass("menuDivider");};this.removeLabelDivider=function(param){$("#label_"+param).removeClass("menuDivider");$("#scroller_"+param).removeClass("menuDivider");$("#label_"+param).addClass("labelBg");$("#scroller_"+param).addClass("labelBg");};this.enter_focus=function(){main.focusedDom=this;$("#icon_"+curFocus).addClass('icon_'+curFocus+'_cursor');$('.icon_'+curFocus+'_cursor').css("border","3px solid "+main.theme);if(curFocus!==openedIndex){$("#callOut_"+curFocus).css("display","block");$("#callOutArr_"+curFocus).css("display","block");}else{$("#scroller_"+curFocus).addClass('orangeColor');$(".orangeColor").css("background-color",main.theme);}};this.leave_focus=function(){$('.icon_'+curFocus+'_cursor').css("border","3px solid transparent");$("#icon_"+curFocus).removeClass('icon_'+curFocus+'_cursor');if(curFocus===openedIndex){$(".orangeColor").css("background-color","");$("#scroller_"+curFocus).removeClass('orangeColor');}
$("#callOut_"+curFocus).css("display","none");$("#callOutArr_"+curFocus).css("display","none");};function moveProducts(param){switch(param){case'left':$("#scroller_2").css("right","411px");$("#callOut_2").css("left","103px");$("#callOutArr_2").css("left","112px");break;case'right':$("#scroller_2").css("right","-1px");$("#callOut_2").css("left","446px");$("#callOutArr_2").css("left","525px");break;}}
function moveComments(param){switch(param){case'left':$("#scroller_3").css("right","822px");break;case'right':$("#scroller_3").css("right","410px");break;}}
function moveProductComment(param){switch(param){case'left':moveProducts('left');moveComments('left');break;case'right':moveProducts('right');moveComments('right');break;}}
function resetSelectedIndex(){var position="";$(".icon_"+openedIndex+"_selected").css("background-color","#ddd");$("#icon_"+openedIndex).removeClass('icon_'+openedIndex+'_selected');$(".shaded_selected").css("background-color","");$("#shaded_"+openedIndex).removeClass('shaded_selected');$("#label_"+openedIndex).css("color","#555");switch(openedIndex){case 1:position="0 -786px";break;case 2:position="0 -990px";break;case 3:position="0 -480px";break;}
$(".shaded_"+openedIndex).css("background-position",position);detail.prev=detail.menuObj;}
function openDesc(){detail.descObj.createDescription();switch(openedIndex){case 2:detail.menuObj.removeLabelDivider("1");moveProducts('right');detail.flag=0;break;case 3:detail.menuObj.setLabelDivider("2");detail.menuObj.removeLabelDivider("1");moveProductComment('right');detail.flag=1;break;}
openedIndex=1;$(".shaded_1").css("background-position","0 -888px");}
function openProducts(){detail.descObj.createProductDesc();detail.menuObj.removeLabelDivider("2");switch(openedIndex){case 1:moveProducts('left');detail.flag=2;break;case 3:moveComments('right');detail.flag=3;break;}
openedIndex=2;$(".shaded_2").css("background-position","0 -1194px");}
function openComments(){contentText.innerHTML="";getComments();switch(openedIndex){case 1:moveProductComment('left');detail.flag=4;break;case 2:moveComments('left');detail.flag=5;break;}
openedIndex=3;$(".shaded_3").css("background-position","0 -684px");}
this.createMenu=function(){openedIndex=1;curFocus=1;var menu="<div id='callOut_1' class='callOut'><p class='callOutDesc'>Description</p></div><div id='callOut_2' class='callOut'>Products</div><div id='callOut_3' class='callOut'>Comments</div><div class='slideShadow'></div><div id='slideCont' class='slideCont'><div id='scroller' class='scroller'><div id='scroller_1' class='detailScroller labelBg'><div id='icon_1' class='icon icon_1'><div id='shaded_1' class='shaded'></div><div id='shadedImg_1' class='shaded_1 shadedImg'></div></div><div id='label_1' class='label labelBg'>&nbsp;&nbsp;"+detail.contentType+" DETAILS</div></div><div id='scroller_2' class='detailScroller labelBg'><div id='icon_2' class='icon icon_2'><div id='shaded_2' class='shaded'></div><div id='shadedImg_2' class='shaded_2 shadedImg'></div></div><div id='label_2' class='label labelBg'>&nbsp;PRODUCT DETAILS</div></div><div id='scroller_3' class='detailScroller labelBg'><div id='icon_3' class='icon  icon_3'><div id='shaded_3' class='shaded'></div><div id='shadedImg_3' class='shaded_3 shadedImg'></div></div><div id='label_3' class='label labelBg'>&nbsp;COMMENTS</div></div></div></div><div id='callOutArr_1' class='callOutArr'></div><div id='callOutArr_2' class='callOutArr'></div><div id='callOutArr_3' class='callOutArr'></div>";detailLeft.innerHTML+=menu;$("#icon_1").addClass('icon_1_selected');$("#shaded_1").addClass('shaded_selected');$(".shaded_selected").css("background-color",detail.icon);$(".shaded_1").css("background-position","0 -888px");detail.descObj.disableMenu();detail.menuObj.setLabelDivider("2");detail.menuObj.removeLabelDivider("1");$("#scroller_2").bind("transitionend webkitTransitionEnd",function(){if(detail.flag===4){detail.menuObj.setLabelDivider("2");detail.menuObj.setLabelDivider("1");}
if(detail.flag===2){detail.menuObj.setLabelDivider("1");}
if(detail.flag===0){detail.menuObj.setLabelDivider("2");}});$("#scroller_3").bind("transitionend webkitTransitionEnd",function(){if(detail.flag===3){detail.menuObj.setLabelDivider("1");detail.menuObj.removeLabelDivider("2");}
if(detail.flag===5){detail.menuObj.setLabelDivider("2");detail.menuObj.setLabelDivider("1");}});};this.setDescFocus=function(){var i;detail.prev=this;this.leave_focus();for(i=3;i>0;i--){if(!$("#icon_"+i).hasClass("disabled")){curFocus=i;break;}}
detail.descObj.enter_focus();};this.KeyboardEvent=function(e,eventType){var target=main.target(e),keyCode=target.keyCode,key=main.keyCodeDic[keyCode],i;if(eventType==="keydown"){switch(key){case"arrowdown":return false;case"arrowup":if(detail.galleryObj.components.length>1||detail.hasVideo){this.leave_focus();detail.galleryObj.enter_focus();}else{this.leave_focus();detail.oldCursor=this;detail.prevCursor=this;main.mainBg.enter_focus();}
return false;case"arrowleft":if(curFocus!==1){this.leave_focus();curFocus-=1;while(curFocus>1){if($("#icon_"+curFocus).hasClass("disabled")){curFocus-=1;}else{break;}}
this.enter_focus();}
return false;case"arrowright":if(curFocus!==3){this.leave_focus();curFocus+=1;while(curFocus<3){if($("#icon_"+curFocus).hasClass("disabled")){curFocus+=1;}else{break;}}
if($("#icon_"+curFocus).hasClass("disabled")&&curFocus===3){detail.prev=this;for(i=3;i>0;i--){if(!$("#icon_"+i).hasClass("disabled")){curFocus=i;break;}}
detail.descObj.enter_focus();}else{this.enter_focus();}}else{this.setDescFocus();}
return false;case"ok":if(curFocus!==openedIndex){detail.prevSelected=openedIndex;resetSelectedIndex();switch(curFocus){case 1:openDesc();break;case 2:openProducts();break;case 3:openComments();break;}
this.leave_focus();$("#shaded_"+openedIndex).addClass('shaded_selected');$(".shaded_selected").css("background-color",detail.icon);$("#label_"+openedIndex).css("color",main.theme);}
break;}
return false;}};}
detail.menuObj=new detail.menuContainer();detail.galleryContainer=function(){var moveLeft=0,obj={},imgCount=1,start=0;this.components=[];this.enter_focus=function(){main.focusedDom=this;$(".leftCont").addClass("rightCont_cur");$(".leftCont").css("border","4px solid "+main.theme);}
this.leave_focus=function(){$(".leftCont").removeClass("rightCont_cur");$(".leftCont").css("border","4px solid transparent");}
obj.enableleftArrow=function(){$("#leftArr").addClass('galleryLeftEnabled');$(".galleryLeftEnabled").css("background-color",main.theme);};obj.enablerightArrow=function(){$("#rightArr").addClass('galleryRightEnabled');$(".galleryRightEnabled").css("background-color",main.theme);};obj.enableBothArrow=function(){obj.enableleftArrow();obj.enablerightArrow();};obj.disableBothArrow=function(){$(".galleryRightEnabled").css("background-color","#dbdbdb");$(".galleryLeftEnabled").css("background-color","#dbdbdb");$("#leftArr").removeClass("galleryLeftEnabled");$("#rightArr").removeClass("galleryRightEnabled");};obj.hideArrow=function(){$("#leftArr").css("visibility","hidden");$("#rightArr").css("visibility","hidden");};obj.showArrow=function(){$("#leftArr").css("visibility","visible");$("#rightArr").css("visibility","visible");}
function gallery_baseGrid(param){var config=param||{},obj=null,imgString="",imageVal="";imgString="<img onload='imgOnload(this)' onerror='imgOnerror(this)' class='imgGallery' id='imgGallery_"+config.id+"'src='";imageVal=(config.videoId?(imgString+(config.videoImg?config.videoImg:"images/default_image.png")+"'/><div class='detailPlayIcon'></div><div class='playerHover'>Press OK to play Video</div>"):(config.src?(imgString+config.src+"'/>"):(imgString+"images/default_image.png"+"'/>")));obj={"wrapper":"<div class='imgWrapper' id='imgWrapper_"+config.id+"'></div>","loadingText":"<div class='imgLoading' id='imgLoading_"+config.id+"'>Loading...</div>","image":imageVal};gallerySlideCont.innerHTML+=obj.wrapper;obj.wrapper=document.getElementById("imgWrapper_"+config.id);obj.wrapper.innerHTML=obj.loadingText;obj.wrapper.innerHTML+=obj.image;obj.image=document.getElementById("imgGallery_"+config.id);obj.loadingText=document.getElementById("imgLoading_"+config.id);obj.videoId=config.videoId||null;obj.hasVideoId=function(){return(obj.videoId)?true:false;};obj.getVideoId=function(){return(obj.videoId);};imgOnload=function(image){$(image).prev().css("display","none");}
imgOnerror=function(image){$(image).prev().css("display","none");$(image).attr("src","images/default_image.png");}
return obj;}
this.getYouTubeData=function(list){detail.videoArr=list.Result[main.selectedGrid].Medias.filter(function(value){return value.YoutubeVideoId;});detail.normalArr=list.Result[main.selectedGrid].Medias.filter(function(value){return value.YoutubeVideoId===null;});};this.gridCreate=function(param,data){var item=0;for(item=0;item<param.length;item++){this.components[start]=gallery_baseGrid({'id':start,'src':(param&&param[item].SmallPictureUri)?param[item].SmallPictureUri:null,'videoId':(param&&param[item].YoutubeVideoId)?param[item].YoutubeVideoId:null,'videoImg':(param&&param[item].YoutubeVideoThumbnailUri?param[item].YoutubeVideoThumbnailUri:null)});start++;}};this.thumbnail=function(data){var len;this.free();if(detail.contentType==="Gallery"){if(data.Result[main.selectedGrid].Media){this.components[0]=gallery_baseGrid({'id':0,'src':(data.Result[main.selectedGrid].Media.SmallPictureUri?data.Result[main.selectedGrid].Media.SmallPictureUri:null),'videoId':null});this.gallery_products();}else{this.components[0]=gallery_baseGrid({'id':0,'src':null,'videoId':null});}}else{obj.disableBothArrow();obj.hideArrow();if(data.Result[main.selectedGrid].Medias&&data.Result[main.selectedGrid].Medias.length>0){this.getYouTubeData(data);if(detail.videoArr.length>0){this.gridCreate(detail.videoArr,data);detail.hasVideo=true;}
if(detail.normalArr.length>0){this.gridCreate(detail.normalArr,data);}
if(detail.normalArr.length===0&&detail.videoArr.length===0){this.components[0]=gallery_baseGrid({'id':0,'src':null,'videoId':null});}
if(detail.contentType==="Product"){this.gallery_products();}
len=this.components.length*502;$("#gallerySlideCont").css("width",len+"px");}}
if(this.components.length>1&&detail.contentType!=="Gallery"){obj.showArrow();obj.enablerightArrow();}};this.productGallery=function(data){var item,len;this.free();obj.hideArrow();for(index=0,item=0;item<data.Result[main.selectedGrid].RecommendedProduct.Medias.length;item++,index++){this.components[item]=gallery_baseGrid({'id':item,'src':(data.Result[main.selectedGrid].RecommendedProduct.Medias[item]&&data.Result[main.selectedGrid].RecommendedProduct.Medias[item].SmallPictureUri)?data.Result[main.selectedGrid].RecommendedProduct.Medias[item].SmallPictureUri:null,'videoId':null});}
if(data.Result[main.selectedGrid].RecommendedProduct.Medias.length===0){this.components[0]=gallery_baseGrid({'id':0,'src':null,'videoId':null});}
len=this.components.length*502;$("#gallerySlideCont").css("width",len+"px");obj.disableBothArrow();if(this.components.length>1){obj.showArrow();obj.enablerightArrow();}else{obj.hideArrow();}};this.gallery_products=function(){$("#galleryCont").addClass("heightHundred");$("#galleryCont").css("height","777px");$("#detailGalleryCursor").css("height","777px");$("#detailGallery").addClass("heightHundred");$(".leftContShadow").css("height","777px");$(".leftCont").css("height","777px");$("#gallerySlideCont").addClass("heightHundred");$(".imgWrapper").addClass("heightHundred");$(".imgGallery").addClass("prd_gal_maxHeight");$(".imgLoading").addClass("prd_gal_top");$(".detailGallery").css("border","1px solid rgba(0, 0, 0, 0)");$(".leftArr").css("top","343px");$(".leftArr").css("left","0px");$(".rightArr").css("top","343px");$(".rightArr").css("left","10px");};this.createGallery=function(data){var gallery="<div id='detailGalleryCursor' class='detailGalleryCursor'></div><div id='galleryCont' class='galleryCont'><div id='leftArr' class='leftArr'><div id='galleryLeftArr' class='galleryLeftArr'></div></div><div id='detailGallery' class='detailGallery'><div id='gallerySlideCont' class='gallerySlideCont'></div></div><div id='rightArr' class='rightArr'><div id='galleryRightArr' class='galleryRightArr'></div></div></div>";imgCount=1;detailLeft.innerHTML=gallery;this.thumbnail(data);};this.getCurrentItem=function(){return imgCount-1;};this.hasVideoId=function(){return this.components[this.getCurrentItem()].hasVideoId();};this.getVideoId=function(){return this.components[this.getCurrentItem()].getVideoId();};this.free=function(){this.components=[];moveLeft=0;imgCount=1;start=0;gallerySlideCont.innerHTML="";$("#gallerySlideCont").css("width","0px");$("#gallerySlideCont").css("margin-left","0px");$(".galleryRightEnabled").css("background-color","#dbdbdb");$(".galleryLeftEnabled").css("background-color","#dbdbdb");$("#rightArr").removeClass("galleryRightEnabled");$("#leftArr").removeClass("galleryLeftEnabled");};this.scrollLeft=function(){moveLeft-=502;$("#gallerySlideCont").css("margin-left",moveLeft+"px");imgCount+=1;if(imgCount===this.components.length){obj.disableBothArrow();obj.enableleftArrow();}else{obj.enableBothArrow();}};this.scrollRight=function(){moveLeft+=502;$("#gallerySlideCont").css("margin-left",moveLeft+"px");imgCount-=1;if(imgCount===1){obj.disableBothArrow();obj.enablerightArrow();}else{obj.enableBothArrow();}};this.KeyboardEvent=function(e,eventType){target=main.target(e),keyCode=target.keyCode,key=main.keyCodeDic[keyCode];if(eventType==="keydown"){switch(key){case"arrowright":if(imgCount!==this.components.length){this.scrollLeft();}else{detail.prev=this;this.leave_focus();detail.descObj.enter_focus();}
return false;case"arrowleft":if(imgCount!==1){this.scrollRight();}
return false;case"arrowdown":if(detail.contentType!=="Gallery"&&detail.contentType!=="Product"&&detail.disable!=2){this.leave_focus();detail.menuObj.enter_focus();}
return false;case"arrowup":detail.oldCursor=this;detail.prevCursor=this;this.leave_focus();main.mainBg.enter_focus();return false;case"ok":if(this.hasVideoId()){this.leave_focus();playerControls.show(this.getVideoId(),this);};return false;}
return false;}};};detail.galleryObj=new detail.galleryContainer();getComments=function(){"use strict";var URL1=main.baseUrl+main.api.comment+detail.uniqueKey,URL2="&limit=10&subcategory=All";detail.getCommentResponse(URL1,URL2);};isOff=false;detail.createDetailPage=function(param){"use strict";innerSection.innerHTML="";detail.hasVideo=false;detail.prevSelected=1;var obj={},data,title_user="",layout="<header id='detailHeader' class='detailHeader theme'><div class='detailCont'><div id = 'titleCont' class='titleCont'><div id = 'leftMask' class = 'leftMask'></div><div id='headerTitle' class='headerTitle'></div></div><div class='category'><div id='subCategoryImg' class='subCategory'></div><span id='subCategoryUp' class='subCategoryUp'></span></div></div><div class='titleDivider'></div><div id='postedByCont' class='postedByCont'><span class='postedBy'>POSTED BY&nbsp;&nbsp;</span><span id='postedByUser' class='postedByUser'></span><div id='detailReturn' class='detailReturn'><div id='detailReturnText' class='detailReturnText'></div><div id='detailReturnImg' class='detailReturnImg'></div></div></div></header><div class='rightCont'><div class='rightContShadow'></div></div><div id='lowerContainer' class='lowerContainer'><div class='leftCont'><div class='leftContShadow'></div></div><div id='detailLeft' class='detailLeft'></div><div id='detailRight' class='detailRight'><div id='detailTitle' class='detailTitle theme nonFocus'><div id = 'opacityDiv' class = 'opacityDiv hide'></div><span id='subCategory' class='subCategory'></span></div><div id='descContainer' class='descContainer'></div></div></div>";innerSection.innerHTML=layout;data=main.listingData;detail.first=true;obj.setTitle=function(){var userName="";title_user=(data.Result[main.selectedGrid].Title?data.Result[main.selectedGrid].Title:"NO TITILE AVAILABLE.");detail.contentTitle=title_user;detail.contentType=(data.Result[main.selectedGrid].ContentType?data.Result[main.selectedGrid].ContentType:"Recipes");if(param=="GALLERY"&&main.selectedCountry=="MALAYSIA"){subCategoryUp.innerHTML="FOOD DIARY";}else{subCategoryUp.innerHTML=param;}
switch(detail.contentType){case"Recipe":$("#subCategoryImg").css("background-position","0 -384px");$(".postedBy").css("color","#944f00");detail.icon="f8931f";detail.enableDownArrCur=detail.enableUpArrCur="enableUpArrCur_o";$(".titleDivider").css("background-position","0 -195px");break;case"Product":$("#subCategoryImg").css("background-position","0 -288px");$(".postedBy").css("color","#004361");detail.enableDownArrCur=detail.enableUpArrCur="enableUpArrCur_b";$(".titleDivider").css("background-position","0 -73px");break;case"FoodHack":$("#subCategoryImg").css("background-position","0 -96px");$(".postedBy").css("color","#7f1301");detail.icon="#ef4023";detail.enableDownArrCur=detail.enableUpArrCur="enableUpArrCur_r";$(".titleDivider").css("background-position","0 -256px");break;case"Gallery":$("#subCategoryImg").css("background-position","0 -192px");$(".postedBy").css("color","#2f6e03");detail.enableDownArrCur=detail.enableUpArrCur="enableUpArrCur_g";$(".titleDivider").css("background-position","0 -134px");break;default:$("#subCategoryImg").css("background-position","0 0");$(".postedBy").css("color","#7f1301");detail.icon="#ef4023";detail.enableDownArrCur=detail.enableUpArrCur="enableUpArrCur_r";$(".titleDivider").css("background-position","0 -256px");}
title_user=(data.Result[main.selectedGrid].Owner&&data.Result[main.selectedGrid].Owner.Name)?data.Result[main.selectedGrid].Owner.Name:"-";postedByUser.innerHTML=title_user;if(main.categoryCode=="RECIPES"){detailReturnText.innerHTML="RETURN TO RECIPES LIST";}else if(main.categoryCode=="FOODHACKS"){detailReturnText.innerHTML="RETURN TO FOODHACKS LIST";}else if(main.categoryCode=="PRODUCTS"){detailReturnText.innerHTML="RETURN TO PRODUCTS LIST";}else if(main.categoryCode=="GALLERY"){if(main.selectedCountry=="MALAYSIA"){detailReturnText.innerHTML="RETURN TO FOOD DIARY LIST";}else{detailReturnText.innerHTML="RETURN TO GALLERY LIST";}}else if(main.categoryCode=="FOOD DIARY"){detailReturnText.innerHTML="RETURN TO FOOD DIARY LIST";}else if(main.categoryCode=="FEATURED"){detailReturnText.innerHTML="RETURN TO FEATURED LIST";}else if(main.categoryCode=="Search"){detailReturnText.innerHTML="RETURN TO SEARCH RESULT LIST";}};obj.textScroll=function(){try{var split_title=detail.contentTitle,split_title_cpy=detail.contentTitle,split_title_cpy1="",divStr="",str="",index=0,spanObj,total=0,loopVar=0,arr=[];split_title_cpy1=detail.contentTitle.split(" ");split_title=split_title_cpy1;var tempBg=main.createElement('div',{classname:'tempBgDetail',id:'tempBgDetail',});tempBg.style.position="absolute";if(main.isAvailable("tempBgDetail"))
$("#tempBgDetail").remove();$("body").append(tempBg);detail.tempArr=[];while(total<split_title_cpy1.length){for(loopVar=0;loopVar<split_title.length;loopVar++,total++){str=split_title[loopVar];str+=" ";tempBg.innerHTML+=str;if(tempBg.scrollWidth>$(".titleCont").width()){tempBg.innerHTML=tempBg.innerHTML.substring(0,tempBg.innerHTML.lastIndexOf(split_title[loopVar]));detail.tempArr[index]=tempBg.innerHTML;tempBg.innerHTML="";loopVar--;index++;}}}
detail.tempArr[index]=tempBg.innerHTML;$("#tempBgDetail").addClass('hide');detail.titlePage=0;document.getElementById('headerTitle').innerHTML=detail.tempArr[detail.titlePage];var self=obj;if(detail.tempArr.length>1){detail.titlePage+=1;detail.timer=setInterval(function(){self.setLeft();},5000);}}catch(e){}};obj.setLeft=function(){document.getElementById('headerTitle').innerHTML="";document.getElementById('headerTitle').innerHTML=detail.tempArr[detail.titlePage];detail.titlePage+=1;var arrLength=(detail.tempArr.length)-1;if(detail.titlePage>arrLength){detail.titlePage=0;}}
obj.setTitle();detail.descObj.createDescription(data);detail.galleryObj.createGallery(data);if(detail.contentType!=="Gallery"&&detail.contentType!=="Product"){detail.menuObj.createMenu();}else{detail.prev=(detail.galleryObj.components.length>1||detail.hasVideo?detail.galleryObj:null);}
detail.descObj.setTheme();obj.textScroll();$("#label_1").css("color",main.theme);}
detail.getCommentResponse=function(baseUrl,param){main.loading.On();main.fromComment=true;var URL=main.generateUrl(baseUrl,param),commentData=null;try{$.ajax({type:"POST",url:URL,timeout:30000,success:function(data){main.loading.Off();commentData=main.getData(data);detail.descObj.createComments(commentData);},error:function(jqXHR,textStatus,errorThrown){main.loading.Off();detail.descObj.createComments(commentData);}});}catch(e){main.loading.Off();detail.descObj.createComments(commentData);}};